# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: DotNetCore
  displayName: DotNetCore
  jobs:
    - job: DotNetCore
      displayName: DotNetCore
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '$(Build.SourcesDirectory)/Eze.UnitTests/Eze.UnitTests.csproj'
            
- stage: Docker
  displayName: Docker
  jobs:
  - job: Docker
    displayName: Docker
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ShuntJG'
        repository: 'shuntjg/eze'
        command: 'buildAndPush'
        Dockerfile: '**/**/Dockerfile'
        buildContext: '**/Eze.Api'
    
