# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: Testing ApiController route endpoints
  jobs:
    - job: Test
      displayName: Test
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '$(Build.SourcesDirectory)/Eze.UnitTests/Eze.UnitTests.csproj'
            
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Eze.Api/Dockerfile'
        tags: |
          $(tag)
